# configs/model/baseline_vae.yaml

# Model instantiation for our latent-space VAE wrapper
_target_: src.models.baselines.cnn.vae_module.LatentVAELitModule
#cfg_path: "src/utils/latent_diffusion/models/first_stage_models/kl-f4/config.yaml"
cfg_path: "src/utils/latent_diffusion/models/first_stage_models/kl-f8/config.yaml"
#checkpoint_path: "/home/qd8/models/vae_sd2.ckpt"
allow_resize: true
compile: false
nll_weight: 1.5



